--INSERTS PARA EL AVANCE DEL AVANCE

--FLIA OLFAT
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Verde');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Cítrico');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Flores');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Frutas');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Aromáticos');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Helechos (Fougère)');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Chipre');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Maderas');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Orientales');
INSERT INTO VAM_FLIA_OLFAT(nombre) VALUES ('Otros');

-- OTROS_ING_COMP

--Productor 
INSERT INTO VAM_PRODUCTORES(nombre,email,telefono,pag_web) VALUES ('Firmenich','daaid.lyon@firmenich.com',33170377661,'www.firmenich.com');
INSERT INTO VAM_PRODUCTORES(nombre,email,telefono,pag_web) VALUES ('IFF','michael.deveau@iff.com',12127655500,'iff.com');
INSERT INTO VAM_PRODUCTORES(nombre,email,telefono,pag_web) VALUES ('Estee Lauder Companies','alkumar.ka@elcompanies.com',12122294830,'www.elcompanies.com');
INSERT INTO VAM_PRODUCTORES(nombre,email,telefono,pag_web) VALUES ('L’Occitane','lstrend312@gmail.com',969364656,'fr.loccitane.com');

--Pais 
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Afganistán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Islas Aland');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Albania');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Argelia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Samoa Americana');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Andorra');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Angola');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Anguilla');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Antigua y Barbuda');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Argentina');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Armenia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Aruba');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Australia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Austria');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Azerbaiyán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Bahamas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Bahrein');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Bangladesh');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Barbados');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Bielorrusia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Bélgica');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Belice');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Benin');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Islas Bermudas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Bután');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Bolivia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Bonaire, San Eustaquio y Saba');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Bosnia y Herzegovina');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Botswana');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Isla Bouvet');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Brasil');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Territorio Británico del Océano Índico');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Islas Vírgenes Británicas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Brunei');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Bulgaria');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Burkina Faso');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Burundi');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Cabo Verde');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Camboya');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Camerún');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Canadá');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Islas Caimán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','República Centroafna');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Chad');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Chile');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','China');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','China, Hong Kong, Región Administrativa Especial');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','China, Macao, Región Administrativa Especial');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Isla de Navidad');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Islas Cocos');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Colombia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Comoras');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Congo');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Islas Cook');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Costa Rica');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Costa de Marfil');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Croacia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Cuba');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Curaçao');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Chipre');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Chequia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','República Popular Democrática de Corea');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','República Democrática del Congo');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Dinamarca');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Djibouti');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','dominica');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','República Dominicana');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Ecuador');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Egipto');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','El Salvador');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Guinea Ecuatorial');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Eritrea');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Estonia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Eswatini');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Etiopía');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Islas Malvinas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Islas Faroe');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Fiji');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Finlandia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Francia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Guayana francesa');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Polinesia francés');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Territorios Franceses del Sur');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Gabón');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Gambia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Georgia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Alemania');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Ghana');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Gibraltar');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Grecia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Groenlandia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Granada');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Guadalupe');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Guam');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Guatemala');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Guernesey');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Guinea');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Guinea-Bissau');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Guayana');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Haití');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Islas Heard y McDonald');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Santa Sede');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Honduras');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Hungría');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Islandia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','India');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Indonesia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Irán (República Islámica de)');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Irak');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Irlanda');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Isla del hombre');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Israel');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Italia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Jamaica');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Japón');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Jersey');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Jordán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Kazajstán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Kenia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Kiribati');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Kuwait');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Kirguizistán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','República Democrática Popular de Lao');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Letonia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Líbano');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Lesoto');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Liberia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Libia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Liechtenstein');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Lituania');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Luxemburgo');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Madagascar');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Malawi');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Malas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Maldivas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','mali');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Malta');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Islas Marshall');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Martinica');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Mauritania');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Isla mauricio');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Mayotte');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','México');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Micronesia (Estados Federados de)');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Mónaco');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Mongolia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Montenegro');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Montserrat');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Marruecos');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Mozambique');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Myanmar');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Namibia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Nauru');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Nepal');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Países Bajos');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Nueva Caledonia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Nueva Zelanda');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Nicaragua');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Níger');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Nigeria');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Niue');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Isla Norfolk');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Norte Macedonia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Islas Marianas del Norte');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Noruega');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Omán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Pakistán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Palau');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Panamá');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Papúa Nueva Guinea');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Paraguay');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Perú');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Filipinas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Pitcairn');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Polonia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Portugal');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Puerto Rico');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Katar');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','República de Corea');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','República de Moldova');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Reunión');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Rumania');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Rusia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Ruanda');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','San Bartolomé');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Santa Helena');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Saint Kitts y Nevis');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Santa Lucía');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','San Martín (parte francesa)');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','San Pedro y Miquelón');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','San Vicente y las Granadinas');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Samoa');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','San Marino');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Santo Tomé y Príncipe');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Sark');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Arabia Saudita');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Senegal');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Serbia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Seychelles');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Sierra Leona');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Singapur');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Sint Maarten (parte neerlandesa)');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Eslovaquia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Eslovenia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Islas Salomón');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Somalia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Sudáfrica');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Georgia del sur y las islas Sandwich del sur');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Sudán del Sur');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','España');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Sri Lanka');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Estado de Palestina');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Sudán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Surinam');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Svalbard y Jan Mayen');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Suecia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Suiza');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','República Árabe Siria');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Tayikistán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Tailandia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Timor Oriental');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Ir');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Tokelau');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Tonga');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Trinidad y Tobago');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Túnez');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Turquia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Turkmenistán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Islas Turcas y Caicos');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Tuvalu');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Uganda');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Ucrania');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Emiratos Árabes Unidos');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('e','Reino Unido de Gran Bretaña e Irlanda del Norte');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','República Unida de Tanzania');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Islas periféricas menores de Estados Unidos');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Estados Unidos de America');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Islas Vírgenes de los Estados');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Uruguay');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Uzbekistán');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Vanuatu');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('am','Venezuela (República Bolivariana de)');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Vietnam');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('o','Wallis y Futuna');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Sahara Occidental');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('as','Yemen');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Zambia');
INSERT INTO VAM_PAISES(continente,nombre) VALUES ('af','Zimbabue');

--Proveedor 
INSERT INTO VAM_PROVEEDORES(nombre,email,telefono,pag_web,id_pais) VALUES ('Ultra International Ltd','ultra@ultranl.com',911141517010,'ultranl.com',155);
INSERT INTO VAM_PROVEEDORES(nombre,email,telefono,pag_web,id_pais) VALUES ('Privi Organics Ltd','info@privi.co.in',912233043500,'www.privi.com',106);
INSERT INTO VAM_PROVEEDORES(nombre,email,telefono,pag_web,id_pais) VALUES ('Tennants','contact@tennantsfinechemicals.co.uk',1538399100,'www.tennantsfinechemicals.co.uk',234);
INSERT INTO VAM_PROVEEDORES(nombre,email,telefono,pag_web,id_pais) VALUES ('Mane','yaas.dumont@mane.com',34493097000,'www.mane.com/',237);
INSERT INTO VAM_PROVEEDORES(nombre,email,telefono,pag_web,id_pais) VALUES ('Inoue Pergumery MFG','overseas-div@ino-p.com',81337299147,'www.ino-p.com/en',115);

--PA_PR 
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,217);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,237);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,13);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,14);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,21);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,31);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,46);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,51);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,64);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,80);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,87);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,106);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,113);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,115);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,143);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,160);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,165);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,173);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,201);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,207);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,210);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,220);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,232);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (1,234);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,13);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,46);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,107);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,115);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,179);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,173);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,201);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,220);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,243);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,10);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,45);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,31);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,51);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,143);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,237);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,41);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,80);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,81);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,155);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,183);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,175);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,227);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,210);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,234);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,112);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,207);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,233);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,95);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,47);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,232);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (2,217);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,237);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,31);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,179);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,207);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,234);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,210);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,113);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,87);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,21);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,176);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,51);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,242);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,143);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,183);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,46);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,106);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,13);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,157);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,112);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,217);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,14);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,104);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (3,64);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,211);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,220);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,179);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,243);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,173);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,115);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,46);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,107);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,106);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,41);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,145);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,176);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,175);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,232);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,55);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,125);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,169);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,112);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,12);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,196);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,233);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,68);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,242);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,53);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,160);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,31);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,239);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,45);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,234);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,113);
INSERT INTO VAM_PA_PR(id_productor,id_pais) VALUES (4,90);

--FORMA DE ENVIO
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (1,51,'m',10);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (1,14,'a',20);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (1,112,'t',15);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (2,220,'m',12);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (2,243,'t',20);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (3,13,'m',25);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (3,207,'a',13);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (4,12,'m',23);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (4,179,'a',18);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (5,31,'m',15);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (5,173,'a',8);
INSERT INTO VAM_FORMA_ENVIOS(id_prov,id_pais,tipo,cargo) VALUES (5,87,'t',16);

--FORMA DE PAGO
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (1,'cont',NULL,NULL,NULL,NULL);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (1,'cred',50,6,5,30);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (2,'cont',NULL,NULL,NULL,NULL);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (2,'cred',35,10,7,15);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (3,'cont',NULL,NULL,NULL,NULL);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (3,'cred',20,12,10,15);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (4,'cont',NULL,NULL,NULL,NULL);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (4,'cred',40,5,2,20);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (5,'cont',NULL,NULL,NULL,NULL);
INSERT INTO VAM_FORMA_PAGOS(id_proveedor,tipo,porc_inicial,nro_cuotas,interes_mensual,nro_dia_entre_pago) VALUES (5,'cred',60,12,8,20);

--HIST_IFRA ?FECHA FORMATO
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('1/1/2008',NULL,1,'08/25/2012');
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('5/15/2013',NULL,1,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('2/1/2016',NULL,2,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('6/20/2013',NULL,3,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('8/1/2018',NULL,4,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('11/5/2017',1,NULL,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('12/1/2012',2,NULL,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('9/15/2014',3,NULL,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('4/26/2002',4,NULL,NULL);
INSERT INTO VAM_HISTORICO_IFRA(fecha_inicio,id_proveedor,id_productor,fecha_fin) VALUES ('07/08/2002',5,NULL,NULL);

--ING_ESENCIA
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (8007805,1,'Cassia Oil','n','El aceite de casia se destila al vapor de las hojas de Cinnamomum Cassia, grandes árboles delgados que crecen en las partes del sudeste de China y Birmania y se conoce comúnmente como canela china','Cinnamomum cassia',194,199,'destilación al vapor','se aplica destilación a la temperatura indicada para alcanzar el punto de ebullición, así se obtienen las gotas');
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (8015734,1,'Basil Oil Methyl Chavicol','n','El aceite de albahaca se destila del botánico Ocimum basilicum L. La planta generalmente se cultiva y cosecha por sus hojas, que son populares en todo el mundo en muchos platos de comida','Ocimum basilicum L',216,156,'destilación al vapor.','se aplica destilación a la temperatura indicada para alcanzar el punto de ebullición, así se obtienen las gotas');
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (8016635,1,'Clary Sage Oil','n','Obtenido de los tallos en flor de Salvia sclarea L. Clary Sage es una hierba bienal o perenne que crece hasta 40 cm de altura, mucho más pequeña que la misma especie que crece en Francia y Rusia','Salvia sclarea',187,NULL,'destilación al vapor','se aplica destilación a la temperatura indicada para alcanzar el punto de ebullición, así se obtienen las gotas');
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (586629,2,'Terpinolene-40','q','Es un químico con  una fragancia dulce, fresca, cítrica de pino con un viejo matiz de cáscara de limón.','Mezcla de 1-metil-4-propan-2-ilideneciclohexeno y terpenos',184,61,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (4707475,2,'Prionyl','q','Es un químico en el que prevalecen los olores de musgo de roble, leñoso, fenólico y terroso','2,4-dihidroxi-3,6-dimetilbenzoato de metilo',NULL,100,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (106229,2,'Citronellol 85%','q','Es un químico que representa olores como floral, cítrico y una nota ligeramente cerosa','3,7-dimetil-6-octen-1-ol',166,98,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (78605966,3,'Aldehído Cinámico Amilo','q','Un líquido amarillo claro con un olor floral, ligeramente graso que recuerda al jazmín cuando se diluye. Una opción popular para crear notas de jazmín que requieren una cierta inflexión grasa','Alfa trans-n-amilcinamaldehído',NULL,NULL,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (140114,3,'Acetato de Benzilo','q','Como componente principal en los aceites de jazmín y gardenia, el acetato de bencilo ocupa una posición destacada en la industria de sabores y fragancias','Éster bencílico del ácido acético',NULL,NULL,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (142927,3,'Acetato de Hexilo','q','Un éster con un olor dulce, afrutado, a bayas y a pera. Uno de los ésteres de hexilo más populares, se usa en composiciones de sabor para una variedad de tonos de bayas y frutas','Éster hexil de ácido acético',338,56,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (110383,4,'Decanoato de etilo','q','También conocido como caprato de etilo, es un éster de ácido graso formado a partir de ácido cáprico y etanol','C12 H24O2',245,102,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (8015956,4,'Cinnamon','q','Aceite de esencia de hojas de safrol reducido','Cinamaldehído',249,160,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (8007010,4,'Aceite Rosa centifolia','n','también denominada rosa de Provenza o rosa repollo o rosa de mayo es un híbrido de rosa conseguido en el siglo XVII','Rosa X Centifolia',176,NULL,'Hidrodestilación','método de extracción de aceites esenciales en el cual el material esta sumergido en agua en ebullición, la característica principal de este proceso es el contacto directo del agua y el material del cual se extraerá el aceite esencial.');
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (656531,5,'Acetato de sulfurilo','q','Líquido con aromas de nuez, aroma de frijol, aroma de leche, aroma de carne. Se puede observar que posee un color amarillo claro traslúcido','Acetato de 4-metil-5-tiazoliletilo',259,80,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (29957435,5,'Hotrienol','q','Amaderado floral fresco','3,7-dimetil-1,5,7-octatrien-3-ol',228,89,NULL,NULL);
INSERT INTO VAM_INGREDIENTE_ESENCIAS(cas,id_proveedor,nombre,tipo,descripcion,taxonomia,pto_ebu,pto_inflam,proc_extrac,descrip_proceso) VALUES (134203,5,'Antranilato de metilo','q','Amina que se suele utilizar como ingrediente recto en la combinación con aldehídos y cetonas. Líquido fluido transparente/sólido. Color de incoloro a amarillo pálido','C8 H9 N O2',256,NULL,NULL,NULL);

--ING_PRESENTACION
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8007805,1,50,23);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8007805,1,100,40);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8015734,1,1000,215);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8016635,1,10,10);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (586629,2,5000,20);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (586629,2,170000,600);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (586629,2,900000,3000);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (4707475,2,15000,53);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (106229,2,180000,540);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (106229,2,5000,17);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (78605966,3,100,55);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (140114,3,100,3);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (140114,3,10000,2500);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (142927,3,20,13);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (110383,4,1,52);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (110383,4,5,233);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8015956,4,1000,114);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8015956,4,5000,564);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8007010,4,1000,9);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8007010,4,5000,42);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (8007010,4,25000,160);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (656531,5,100,103);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (656531,5,1000,357);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (29957435,5,100,148);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (134203,5,250,24);
INSERT INTO VAM_ING_PRESENTACIONES(cas_ingrediente,id_proveedor,volumen,precio) VALUES (134203,5,1000,79);

--ING_ORIGEN

--ING_OTRO

--FLIA_IE 
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (8,8007805,1);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (5,8015734,1);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (1,8016635,1);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (2,586629,2);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (8,4707475,2);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (6,4707475,2);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (2,106229,2);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (3,106229,2);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (3,78605966,3);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (3,140114,3);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (4,142927,3);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (3,110383,4);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (1,110383,4);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (8,8015956,4);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (3,8007010,4);
INSERT INTO VAM_FLIA_IE(id_flia_olfat,id_ing_esencia,id_ing_prov) VALUES (3,29957435,5);
